member_choices = {
    '1':1,
    '2':2,
    '3':3,
    '4':4,
    '5':5,
    '6':6,
    '7':7,
    '8':8,
    '9':9,
    '10':10,
}

price_choices = {
    '1000' : 'Rs.1000',
    '2000' : 'Rs.2000',
    '3000' : 'Rs.3000',
    '4000' : 'Rs.4000',
    '5000' : 'Rs.5000',
    '6000' : 'Rs.6000',
    '7000' : 'Rs.7000',
    '8000' : 'Rs.8000',
    '9000' : 'Rs.9000',
    '10000' : 'Rs.10k+',
}

state_choices = {
    '1':'1',
    '2':'2',
    '3':'3',
    '4':'4',
    '5':'5',
    '6':'6',
    # 'AL':'Alabama', 
    # 'AK':'Alaska', 
    # 'AZ':'Arizona', 
    # 'AR':'Arkansas', 
    # 'CA':'California', 
    # 'CO':'Colorado', 
    # 'CT':'Connecticut',
    # 'DE':'Delaware', 
    # 'FL':'Florida', 
    # 'GA':'Georgia',
    # 'HI':'Hawaii', 
    # 'ID':'Idaho', 
    # 'IL':'Illinois',
    # 'IN':'Indiana', 
    # 'IA':'Iowa',
    # 'KS':'Kansas', 
    # 'KY':'Kentucky',
    # 'LA':'Louisiana',
    # 'ME':'Maine', 
    # 'MD':'Maryland', 
    # 'MA':'Massachusetts',
    # 'MI':'Michigan', 
    # 'MN':'Minnesota',
    # 'MS':'Mississippi',
    # 'MO':'Missouri', 
    # 'MT':'Montana', 
    # 'NE':'Nebraska',
    # 'NV':'Nevada',
    # 'NH':'New Hampshire',
    # 'NJ':'New Jersey',
    # 'NM':'New Mexico',
    # 'NY':'New York', 
    # 'NC':'North Carolina', 
    # 'ND':'North Dakota',
    # 'OH':'Ohio', 
    # 'OK':'Oklahoma',
    # 'OR':'Oregon',
    # 'PA':'Pennsylvania',
    # 'RI':'Rhode Island',
    # 'SC':'South Carolina', 
    # 'SD':'South Dakota', 
    # 'TN':'Tennessee', 
    # 'TX':'Texas',
    # 'UT':'Utah', 
    # 'VT':'Vermont',
    # 'VA':'Virginia', 
    # 'WA':'Washington',
    # 'WV':'West Virginia',
    # 'WI':'Wisconsin',
    # 'WY':'Wyoming',
}